version: 2.1

executors:
  macos-executor:
    parameters:
      xcode_version:
        description: 'Xcode version'
        default: "11.1.0"
        type: string
    macos:
      xcode: << parameters.xcode_version >>
    environment:
      XCODE_PATH: /Applications/Xcode.app
      FASTLANE_SKIP_UPDATE_CHECK: 1
      LC_ALL: en_US.UTF-8
      LANG: en_US.UTF-8
      FL_OUTPUT_DIR: output
      FL_SLATHER_OUTPUT_DIRECTORY: output/slather
    working_directory: /Users/distiller/project

jobs:
  test:
    parameters:
      xcode_version:
        type: string
    executor:
      name: macos-executor
      xcode_version: << parameters.xcode_version >>
    steps:
      - run: cd /tmp; git clone git@github.com:circleci-book/ios-sample-matchfile.git
      - checkout
      - restore_cache:
          key: gems-v1-{{ checksum "Gemfile.lock" }}
      - run:
          name: 'Install gems with Bundler'
          command: bundle install --path vendor/bundle --clean
      - save_cache:
          key: gems-v1-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run:
          name: Fastlane
          command: bundle exec fastlane test
      - store_artifacts:
          path: output
      - store_test_results:
          path: output/scan

  generate-ipa:
    executor: macos-executor
    steps:
      - checkout
      - restore_cache:
          key: gems-v1-{{ checksum "Gemfile.lock" }}
      - run:
          name: 'Install gems with Bundler'
          command: bundle install --path vendor/bundle --clean
      - run:
          name: Fastlane
          command: bundle exec fastlane adhoc
      - store_artifacts:
          path: output/Game.ipa

workflows:
  version: 2
  build-test-adhoc:
    jobs:
      - test:
          name: test_10-1-0
          xcode_version: "10.1.0"
      - test:
          name: test_11-1-0
          xcode_version: "11.1.0"
      - generate-ipa:
          filters:
            branches:
              only: development
          requires:
            - test_10-1-0
            - test_11-1-0
      #- beta:
          #filters:
            #branches:
              #only: master
          #requires:
            #- build-and-test
