version: 2.1

executors:
  macos-executor:
    macos:
      xcode: "11.1.0"
    environment:
      XCODE_PATH: /Applications/Xcode.app
      FASTLANE_SKIP_UPDATE_CHECK: 1
      LC_ALL: en_US.UTF-8
      LANG: en_US.UTF-8
      FL_OUTPUT_DIR: output
    working_directory: /Users/distiller/project

jobs:
  test:
    executor:
      name: macos-executor
    steps:
      - checkout
      - run:
          name: Set Ruby Version
          command:  echo "ruby-2.6" > ~/.ruby-version
      - restore_cache:
          key: gems-v1-{{ checksum "Gemfile.lock" }}
      - run:
          name: 'Install gems with Bundler'
          command: bundle install --path vendor/bundle --clean
      - save_cache:
          key: gems-v1-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run:
          name: Fastlane
          command: bundle exec fastlane scan
      - store_artifacts:
          path: output
      - store_test_results:
          path: output/scan

  generate-ipa:
    executor: macos-executor
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "f1:c9:e1:35:7d:92:67:d4:e8:b7:54:7e:15:36:1c:5a"
      - restore_cache:
          key: gems-v1-{{ checksum "Gemfile.lock" }}
      - run:
          name: 'Install gems with Bundler'
          command: bundle install --path vendor/bundle --clean
      - run:
          name: Fastlane
          command: bundle exec fastlane adhoc
      - store_artifacts:
          path: output/Game.ipa

workflows:
  version: 2
  build-test-adhoc:
    jobs:
      - test
      - generate-ipa:
          requires:
            - test
      #- beta:
          #filters:
            #branches:
              #only: master
          #requires:
            #- build-and-test
